<!-- DataTables -->
<link rel="stylesheet" href="/dist/plugins/datatables.net-bs/css/dataTables.bootstrap.min.css">
<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title"><?= $title ?></h3>
                <div class="pull-right box-tools">
                    <a href="/novel/collect/set.html" class="btn btn-default"><i class="fa fa-plus"></i></a>
                </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <table id="dList" class="table table-bordered table-hover">
                    <thead>
                    <tr>
                        <th width="20">ID</th>
                        <th>小说封面</th>
                        <th>小说名称</th>
                        <th>已采章节数</th>
                        <th>待采章节数</th>
                        <th>待上传OSS数</th>
                        <th>状态</th>
                        <th>采集ID</th>
                        <th>来源ID</th>
                        <th>采集时间</th>
                        <th width="80">是否采集</th>
                        <th width="150">操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php if (!empty($data)): ?>
                        <?php foreach ($data as $val): ?>
                            <tr>
                                <td><?= $val['id'] ?></td>
                                <td><img src="<?= empty($val['book_img']) ? '/dist/img/booknopic.gif' : $val['book_img'] ?>" width="40"></td>
                                <td><?= $val['book_name'] ?></td>
                                <td><?= $val['book_articlenum'] ?></td>
                                <td><a href="/novel/collect/waitCollectArticle.html?id=<?= $val['id'] ?>&collect_id=<?=$val['book_collect_id']?>"> <?= $val['waitArticleNum'] ?></a></td>
                                <td><?= $val['ossArticleNum'] ?></td>
                                <td><?= $val['book_state'] == 0 ? '<span class="red">连载</span>' : '<span class="green">完本</span>' ?></td>
                                <td><?= $val['book_collect_id'] ?></td>
                                <td><?= $val['book_from_article_id'] ?></td>
                                <td><?= $val['book_last_collect_time'] == '1970-01-01 08:00:00' ? '' : $val['book_last_collect_time'] ?></td>
                                <td><?=(1 === (int)$val['book_is_collect']) ? '<span class="green cursor isCollect" data-id="'.$val['id'].'" data-collect="1">是</span>' : '<span class="red cursor isCollect" data-id="'.$val['id'].'" data-collect="0">否</span>'?></td>
                                <td>
                                    <?php if (1 === (int)$val['book_is_collect']):?>
                                    <a href="/novel/collect/book.html?id=<?= $val['id'] ?>&collect_id=<?=$val['book_collect_id']?>&target_id=<?=$val['book_from_article_id']?>" title="采集">采集</a>
                                    <a href="/novel/collect/oss.html?book_id=<?= $val['id'] ?>">上传OSS</a>
                                    <?php endif;?>
                                    <a href="javascript:;" class="clearAll" data-id="<?= $val['id'] ?>">清空</a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    <?php else:?>
                        <tr><td colspan="11" class="text-center">暂无数据</td></tr>
                    <?php endif; ?>
                    </tbody>
                </table>
                <div class="row text-center" id="pageList">
                </div>
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
    <!-- /.col -->
</div>
<!-- /.row -->
<div class="modal fade" id="clear-modal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">清空小说文章</h4>
            </div>
            <div class="modal-body">
                <p>测试</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">确定</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->
<script src="/dist/plugins/datatables.net/js/jquery.dataTables.min.js"></script>
<script src="/dist/plugins/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
<script>
    $(function () {
        pageHtml(<?=$page?>, <?=$totalPage?>, '<?=$pageLink?>');
        $('.clearAll').click(function () {
            if (!confirm('确定清空已采集文章？')) {
                return false;
            }
            let book_id = $(this).data('id');
            clearArticle(book_id);
            $('#clear-modal').modal().find('.modal-body').html('');
        });
        $('#dList').on('click', '.isCollect', function () {
            var id = $(this).data('id');
            var isCollect = $(this).data('collect') == 1 ? 0 : 1;
            var obj = $(this);
            $.post('/novel/book/isCollect.html', {id:id, isCollect:isCollect}, function (res) {
                if (res.code == 0) {
                    var html = '<span class="' + (isCollect == 1 ? 'green' : 'red') + ' cursor isCollect" data-id="'+id+'" data-collect="'+isCollect+'">' + (isCollect == 1 ? '是' : '否') + '</span>';
                    obj.closest('td').html(html);
                } else {
                    alertMsg('error', res.msg)
                }
            })
        })
    })
    
    function clearArticle(id) {
        $.post('/novel/book/clearArticle.html', {id:id},function (res) {
            if (res.code == 0) {
                $('#clear-modal .modal-body').append('<p>清空成功</p>');
                setTimeout(function(){ window.location.reload(); }, 2000);
            } else if(res.code == 200) {
                clearArticle(id);
                $('#clear-modal .modal-body').append(res.msg);
            } else {
                $('#clear-modal .modal-body').append(res.msg);
            }
        });
    }
</script>