<!-- DataTables -->
<link rel="stylesheet" href="/dist/plugins/datatables.net-bs/css/dataTables.bootstrap.min.css">
<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title"><?= $title ?></h3>
                <div class="pull-right box-tools">
                    <a href="/novel/collect/set.html" class="btn btn-default"><i class="fa fa-plus"></i></a>
                </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <table id="example2" class="table table-bordered table-hover">
                    <thead>
                    <tr>
                        <th width="20">ID</th>
                        <th>小说封面</th>
                        <th>小说名称</th>
                        <th>已采章节数</th>
                        <th>待采章节数</th>
                        <th>待上传OSS数</th>
                        <th>状态</th>
                        <th>采集ID</th>
                        <th>来源ID</th>
                        <th>采集时间</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php if (!empty($data)): ?>
                        <?php foreach ($data as $val): ?>
                            <tr>
                                <td><?= $val['id'] ?></td>
                                <td><img src="<?= empty($val['book_img']) ? '/dist/img/booknopic.gif' : $val['book_img'] ?>" width="40"></td>
                                <td><?= $val['book_name'] ?></td>
                                <td><?= $val['book_articlenum'] ?></td>
                                <td><?= $val['waitArticleNum'] ?></td>
                                <td><?= $val['ossArticleNum'] ?></td>
                                <td><?= $val['book_state'] == 0 ? '<span class="red">连载</span>' : '<span class="green">完本</span>' ?></td>
                                <td><?= $val['book_collect_id'] ?></td>
                                <td><?= $val['book_from_article_id'] ?></td>
                                <td><?= $val['book_last_collect_time'] == '1970-01-01 08:00:00' ? '' : $val['book_last_collect_time'] ?></td>
                                <td><a href="/novel/collect/book.html?id=<?= $val['id'] ?>&collect_id=<?=$val['book_collect_id']?>&target_id=<?=$val['book_from_article_id']?>" title="采集">采集</a>
                                    <a href="/novel/collect/oss.html?book_id=<?= $val['id'] ?>">上传OSS</a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>
                    </tbody>
                </table>
                <div class="row text-center" id="pageList">
                </div>
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
    <!-- /.col -->
</div>
<!-- /.row -->
<script src="/dist/plugins/datatables.net/js/jquery.dataTables.min.js"></script>
<script src="/dist/plugins/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
<script>
    $(function () {
        pageHtml(<?=$page?>, <?=$totalPage?>, '<?=$pageLink?>');
    })
</script>