<div class="row">
    <div class="col-xs-12">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title"><?=$title?></h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <input type="hidden" name="id" value="<?=$data['id'] ?? 0?>">
            <div class="box-body main">
                <div class="col-xs-5"></div>
                <div class="col-xs-7">
                    <?php if ('update' === $act):?>
                    <h4 class="text-aqua">该小说已存在</h4>
                    <a href="javascript:start_collect('/novel/collect/article.html?act=update&book_id=<?=$id?>&target_id=<?=$targetId?>&indexlink=<?=$indexlink?>&collect_id=<?=$collectId?>')" class="btn btn-default">更新该小说</a>
                    <?php elseif ('add' === $act):?>
                    <h4 class="text-success">该小说信息创建成功</h4>
                    <a href="javascript:start_collect('/novel/collect/article.html?act=add&book_id=<?=$id?>&target_id=<?=$targetId?>&indexlink=<?=$indexlink?>&collect_id=<?=$collectId?>')" class="btn btn-default">开始采集文章</a>
                    <?php endif;?>
                </div>
            </div>
            <!-- /.box-body -->

        </div>
        <!-- /.box -->
    </div>
    <!-- /.col -->
</div>
<!-- /.row -->
<script type="text/javascript">
    function start_collect(url){
        $('.main').html('');
        post_url(url);
    }
    function post_url(url){
        $.get(url,echoresult);
    }
    function echoresult(result){
        $('.main').append(result.msg);
        if(result.url != '' && result.url != null){
            setTimeout(post_url(result.url),100);
        }
    }
    function invalid(id, obj) {
        $.get('/novel/collect/confirmFrom?id='+id,function (res) {
            if (res.code == 0) {
                obj.innerHTML = '已确认';
            } else {
                alertMsg('error', res.msg)
            }
        });
    }
</script>