<div class="row">
    <div class="col-xs-12">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title"><?=$title?></h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <input type="hidden" name="id" value="<?=$data['id'] ?? 0?>">
            <div class="box-body main">
                共有<?=$ossArticleNum?>篇文章需上传：<br/>
            </div>
            <!-- /.box-body -->

        </div>
        <!-- /.box -->
    </div>
    <!-- /.col -->
</div>
<!-- /.row -->
<script type="text/javascript">
    post_url('/novel/collect/oss.html?book_id=<?=$bookId?>&key=0');
    function post_url(url){
        $.get(url,echoresult);
    }
    function echoresult(result){
        $('.main').append(result.msg);
        if(result.url != '' && result.url != null){
            setTimeout(post_url(result.url),100);
        }
    }
    function invalid(id, obj) {
        $.get('novel/collect/confirmFrom?id'+id,function (res) {
            if (res.code == 0) {
                obj.innerHTML = '已确认';
            } else {
                alertMsg('error', res.msg)
            }
        });
    }
</script>