<div class="row">
    <div class="col-xs-12">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title"><?=$title?></h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <?php if($act === 'one'):?>
            <form class="form-horizontal" method="get" action="">
                <input type="hidden" name="id" value="<?=$info['id'] ?? 0?>">
                <div class="box-body">
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-2 control-label">来源网站</label>
                        <div class="col-sm-10">
                            <?=$info['collect_host']?>（<?=$info['collect_name']?>）
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-2 control-label">来源文章序号</label>
                        <div class="col-sm-10">
                            <input type="text" name="target_id" value=""/>
                        </div>
                    </div>
                </div>
                <!-- /.box-body -->

                <div class="box-footer">
                    <div class="col-sm-2"></div>
                    <div class="col-sm-10">
                        <input type="hidden" name="act" value="co_intro">
                        <button type="submit" class="btn btn-primary btnSubmit">下一步</button>
                    </div>
                </div>
            </form>
            <?php elseif ($act === 'co_intro'):?>
                <form class="form-horizontal" method="post" action="/novel/collect/book.html">
                    <div class="box-body">
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">书名</label>
                            <div class="col-sm-10">
                                <input type="text" name="book_name" class="form-control" value="<?=$book['book_name'] ?? ''?>" size="40"/>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">分类</label>
                            <div class="col-sm-10">
                                <select name="book_sort">
                                    <option value="0">请选择分类</option>
                                    <?php if(!empty($category)):foreach ($category as $key => $val):?>
                                        <option value="<?=$key?>"><?=$val?></option>
                                    <?php endforeach;endif;?>
                                </select> 参考分类：<?=$book['book_sort'] ?? ''?>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">作者</label>
                            <div class="col-sm-10">
                                <input type="text" name="book_author" class="form-control" value="<?=$book['book_author'] ?? ''?>"/>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">状态</label>
                            <div class="col-sm-10">
                                <label><input type="radio" name="book_state" value="0" <?php if((int)$book['book_state'] === 0)echo 'checked="checked"'?>> 连载中</label>
                                <label><input type="radio" name="book_state" value="1" <?php if((int)$book['book_state'] === 1)echo 'checked="checked"'?>> 已完成</label>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">关键字</label>
                            <div class="col-sm-10">
                                <input type="text" name="book_keyword" class="form-control" value="<?=$book['book_keyword'] ?? ''?>"/>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">简介</label>
                            <div class="col-sm-10">
                                <textarea name="book_intro" class="form-control" rows="5"><?=$book['book_intro'] ?? ''?></textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">封面</label>
                            <div class="col-sm-10">
                                <input type="text" name="book_img" value="<?=$book['book_img'] ?? ''?>" size="80"/> <img src="<?=$book['book_img'] ?? ''?>" width="40" height="50"/>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">章节目录indexlink</label>
                            <div class="col-sm-10">
                                <input type="text" name="indexlink" class="form-control" value="<?=$book['indexlink'] ?? ''?>">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">监控采集</label>
                            <div class="col-sm-10">
                                <label><input type="radio" name="monitoring" value="1" checked="checked" > 监控</label>
                                <label><input type="radio" name="monitoring" value="0"> 不监控</label>
                            </div>
                        </div>
                    </div>
                    <!-- /.box-body -->

                    <div class="box-footer">
                        <div class="col-sm-2"></div>
                        <div class="col-sm-10">
                            <input type="hidden" name="id" value="<?=$info['id'] ?? 0?>">
                            <input type="hidden" name="target_id" value="<?=$targetId?>">
                            <button type="submit" class="btn btn-primary btnSubmit">确认开始采集</button>
                        </div>
                    </div>
                </form>
            <?php endif;?>
        </div>
        <!-- /.box -->
    </div>
    <!-- /.col -->
</div>
<!-- /.row -->