<!-- DataTables -->
<link rel="stylesheet" href="/dist/plugins/datatables.net-bs/css/dataTables.bootstrap.min.css">
<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title"><?= $title ?></h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <table id="example2" class="table table-bordered table-hover">
                    <thead>
                    <tr>
                        <th width="20"></th>
                        <th width="20">ID</th>
                        <th width="60">小说ID</th>
                        <th>章节名称</th>
                        <th>排序</th>
                        <th>状态</th>
                        <th>目标网址</th>
                        <th>文章内容地址</th>
                        <th>创建时间</th>
                        <th>更新时间</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php if (!empty($data)): ?>
                        <?php foreach ($data as $val): ?>
                            <tr>
                                <td><input type="checkbox" class="from_checkbox" value="<?= $val['id'] ?>"></td>
                                <td><?= $val['id'] ?></td>
                                <td><?= $val['from_book_id'] ?></td>
                                <td><?= $val['from_title'] ?></td>
                                <td><?= $val['from_sort'] ?></td>
                                <td><?= $val['from_state'] == 0 ? '<span class="red">未采集</span>' : '<span class="green">已采集</span>' ?></td>
                                <td><a href="<?= $val['from_url'] ?>" target="_blank"> <?= $val['from_url'] ?></a></td>
                                <td><?= $val['url'] ?></td>
                                <td><?= $val['create_at'] == '1970-01-01 08:00:00' ? '' : $val['create_at'] ?></td>
                                <td><?= $val['update_at'] == '1970-01-01 08:00:00' ? '' : $val['update_at'] ?></td>
                                <td>
                                    <a href="javascript:;" onclick="invalid(<?= $val['id'] ?>)" title="已采集">已采集</a>
                                    <a href="/novel/book/setArticle.html?book_id=<?= $val['from_book_id'] ?>&title=<?= $val['from_title'] ?>&sort=<?= $val['from_sort'] ?>" target="_blank">添加</a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    <?php else:?>
                        <tr><td colspan="10" class="text-center">暂无数据</td></tr>
                    <?php endif; ?>
                    </tbody>
                    <tfoot>
                    <tr>
                        <td colspan="11">
                            <span style="margin-right:5px "><label><input type="checkbox" id="allSelect"> 全选</label></span>

                            <div class="btn-group">
                                <button type="button" class="btn btn-default">批量</button>
                                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                                    <span class="caret"></span>
                                    <span class="sr-only">Toggle Dropdown</span>
                                </button>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="#" id="batchCollected">已采集</a></li>
                                </ul>
                            </div>
                        </td>
                    </tr>
                    </tfoot>
                </table>
                <div class="row text-center" id="pageList">
                </div>
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
    <!-- /.col -->
</div>
<!-- /.row -->
<script src="/dist/plugins/datatables.net/js/jquery.dataTables.min.js"></script>
<script src="/dist/plugins/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
<script>
    $(function () {
        pageHtml(<?=$page?>, <?=$totalPage?>, '<?=$pageLink?>');
        $('#allSelect').click(function () {
            var isChecked = $(this).prop('checked');
            $('.from_checkbox').each(function () {
                $(this).prop('checked',isChecked);
            });
        });
        $('#batchCollected').click(function () {
            var idArr = [];
            if ($('.from_checkbox:checked').length == 0) {
                alertMsg('error', '请先选择章节');
                return false;
            }
            $('.from_checkbox:checked').each(function () {
                idArr.push($(this).val());
            });
            $.post('/novel/collect/batchConfirmFrom.html',{'id':idArr},function (res) {
                if (res.code == 0) {
                    window.location.reload();
                } else {
                    alertMsg('error', res.msg)
                }
            });
        });
    })
    function invalid(id) {
        if (!confirm('是否确定已采集？')) {
            return false;
        }
        $.get('/novel/collect/confirmFrom.html?id='+id,function (res) {
            if (res.code == 0) {
                window.location.reload();
            } else {
                alertMsg('error', res.msg)
            }
        });
    }
</script>