<!-- DataTables -->
<link rel="stylesheet" href="/dist/plugins/datatables.net-bs/css/dataTables.bootstrap.min.css">
<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title"><?=$title?></h3>
                <div class="pull-right box-tools">
                    <a href="/blog/article/setArticle.html" class="btn btn-default"><i class="fa fa-plus"></i></a>
                </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <table id="example2" class="table table-bordered table-hover">
                    <thead>
                    <tr>
                        <th width="50">ID</th>
                        <th>文章标题</th>
                        <th width="100">文章分类</th>
                        <th width="70">缩略图</th>
                        <th width="100">标签</th>
                        <th width="70">浏览量</th>
                        <th width="60">排序</th>
                        <th width="60">发布</th>
                        <th width="180">创建时间</th>
                        <th width="180">更新时间</th>
                        <th width="100">操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php if(!empty($data)):?>
                        <?php foreach($data as $val):?>
                            <tr>
                                <td><?=$val['id']?></td>
                                <td><?=$val['title']?></td>
                                <td><?=$category[$val['category_id']] ?? ''?></td>
                                <td><?php if(!empty($val['img_url']))echo '<img src="'.$val['img_url'].'" width="60"/>';?></td>
                                <td><?=$val['tags']?></td>
                                <td><?=$val['clicks']?></td>
                                <td><?=$val['sort']?></td>
                                <td><?=(1 == $val['is_push'] ? '<span class="green">是</span>' : '<span class="gray">否</span>')?></td>
                                <td><?=$val['create_at']?></td>
                                <td><?=$val['update_at']?></td>
                                <td><a href="/blog/article/setArticle.html?id=<?=$val['id']?>" class="btn btn-warning"><i class="fa fa-edit"></i></a></td>
                            </tr>
                        <?php endforeach;?>
                    <?php endif;?>
                    </tbody>
                </table>
                <div class="row text-center" id="pageList">
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
    <!-- /.col -->
</div>
<!-- /.row -->
<script>
    $(function () {
        pageHtml(<?=$page?>, <?=$totalPage?>, '<?=$pageLink?>');
    })
</script>