<div class="row">
    <div class="col-xs-12">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title"><?=$title?></h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <form class="form-horizontal" method="post" action="">
                <input type="hidden" name="id" value="<?=$info['id'] ?? 0?>">
                <div class="box-body">
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-2 control-label">栏目标题</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="name" name="name" value="<?=$info['name'] ?? ''?>" placeholder="栏目标题">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-2 control-label">SEO标题</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="seo_name" name="seo_name" value="<?=$info['seo_name'] ?? ''?>" placeholder="SEO标题">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-2 control-label">栏目关键字</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="keyword" name="keyword" value="<?=$info['keyword'] ?? ''?>" placeholder="栏目关键字">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-2 control-label">栏目描述</label>
                        <div class="col-sm-10">
                            <textarea id="description" class="form-control" name="description" rows="10" ><?=$info['description'] ?? ''?></textarea>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-2 control-label">排序</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="sort" name="sort" value="<?=$info['sort'] ?? '50'?>" placeholder="排序">
                        </div>
                    </div>
                </div>
                <!-- /.box-body -->

                <div class="box-footer">
                    <button type="submit" class="btn btn-primary btnSubmit">保存</button>
                </div>
            </form>
        </div>
        <!-- /.box -->
    </div>
    <!-- /.col -->
</div>
<!-- /.row -->
<script>
    $(function () {
        $('.btnSubmit').click(function(){
            if($('#name').val() == '') {
                alertMsg('error', '栏目名称不能为空');
                return false;
            }
        });

    })
</script>