<!-- DataTables -->
  <link rel="stylesheet" href="/dist/plugins/datatables.net-bs/css/dataTables.bootstrap.min.css">
<div class="row">
    <div class="col-xs-12">
      <div class="box">
        <div class="box-header">
          <h3 class="box-title"><?=$title?></h3>
          <div class="pull-right box-tools">
            <a href="/blog/category/setCategory.html" class="btn btn-default"><i class="fa fa-plus"></i></a>
            </div>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
          <table id="example2" class="table table-bordered table-hover">
            <thead>
            <tr>
              <th width="80">ID</th>
              <th>名称</th>
              <th width="150">上级名称</th>
                <th width="80">状态</th>
              <th width="180">创建时间</th>
              <th width="180">更新时间</th>
              <th width="100">操作</th>
            </tr>
            </thead>
            <tbody>
            <?php if(!empty($data)):?>
            <?php foreach($data as $val):?>
            <tr>
              <td><?=$val['id']?></td>
              <td><?=$val['name']?></td>
              <td><?=empty($val['pid']) ? '顶级' : $category[$val['pid']]?></td>
                <td><?=1 === (int)$val['is_deleted'] ? '<span class="red">删除</span>' : '<span class="green">正常</span>'?></td>
              <td><?=$val['create_at']?></td>
              <td><?=$val['update_at']?></td>
              <td><a href="/blog/category/setCategory.html?id=<?=$val['id']?>" class="btn btn-warning"><i class="fa fa-edit"></i></a></td>
            </tr>
            <?php endforeach;?>
            <?php endif;?>
            </tbody>
          </table>
        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->
    </div>
    <!-- /.col -->
  </div>
  <!-- /.row -->
