<!-- DataTables -->
<link rel="stylesheet" href="/dist/plugins/datatables.net-bs/css/dataTables.bootstrap.min.css">
<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title"><?= $title ?></h3>
                <div class="pull-right box-tools">
                    <a href="/novel/book/setArticle.html?book_id=<?=$book_id?>" class="btn btn-default"><i class="fa fa-plus"></i></a>
                </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <table id="example2" class="table table-bordered table-hover">
                    <thead>
                    <tr>
                        <th width="20">ID</th>
                        <th>文章标题</th>
                        <th>所属章节</th>
                        <th>文章排序</th>
                        <th>是否OSS</th>
                        <th>更新时间</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php if (!empty($data)): ?>
                        <?php foreach ($data as $val): ?>
                            <tr>
                                <td><?= $val['id'] ?></td>
                                <td><?= $val['title'] ?></td>
                                <td><?= $chapters[$val['chapter_id']] ?? '' ?></td>
                                <td><?= $val['article_sort'] ?></td>
                                <td><?= (int)$val['is_oss'] === 0 ? '<span class="red">否</span>' : '<span class="green">是</span>' ?></td>
                                <td><?= $val['update_at'] ?></td>
                                <td>
                                    <a href="/novel/book/setArticle.html?book_id=<?=$book_id?>&id=<?= $val['id'] ?>" title="编辑">编辑</a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>
                    </tbody>
                </table>
                <div class="row text-center" id="pageList">
                </div>
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
    <!-- /.col -->
</div>
<!-- /.row -->
<script src="/dist/plugins/datatables.net/js/jquery.dataTables.min.js"></script>
<script src="/dist/plugins/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
<script>
    $(function () {
        pageHtml(<?=$page?>, <?=$totalPage?>, '<?=$pageLink?>');
    })
</script>