<!-- DataTables -->
<link rel="stylesheet" href="/dist/plugins/datatables.net-bs/css/dataTables.bootstrap.min.css">
<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title"><?= $title ?></h3>
                <div class="pull-right box-tools">
                    <a href="/novel/book/setChapter.html?book_id=<?=$book_id?>" class="btn btn-default"><i class="fa fa-plus"></i></a>
                </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <table id="example2" class="table table-bordered table-hover">
                    <thead>
                    <tr>
                        <th width="20">ID</th>
                        <th>分卷名称</th>
                        <th>章节数</th>
                        <th>排序</th>
                        <th>更新时间</th>
                        <th width="120">操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php if (!empty($data)): ?>
                        <?php foreach ($data as $val): ?>
                            <tr>
                                <td><?= $val['id'] ?></td>
                                <td><?= $val['chapter_name'] ?></td>
                                <td><a href="/novel/book/article.html?book_id=<?= $val['book_id'] ?>" title="章节"><?= $val['chapter_articlenum'] ?? '0' ?></a></td>
                                <td><?= $val['chapter_order'] ?></td>
                                <td><?= $val['update_at'] ?></td>
                                <td>
                                    <a href="/novel/book/setChapter.html?book_id=<?=$book_id?>&id=<?= $val['id'] ?>" title="编辑">编辑</a>
                                    <a href="javascript:;" onclick="delArticle(<?= $val['id'] ?>)" title="删除">删除</a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    <?php else:?>
                        <tr><td colspan="7" class="text-center">暂无数据</td></tr>
                    <?php endif; ?>
                    </tbody>
                </table>
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
    <!-- /.col -->
</div>
<!-- /.row -->
<script src="/dist/plugins/datatables.net/js/jquery.dataTables.min.js"></script>
<script src="/dist/plugins/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
<script>
    function delArticle(id) {
        if (!confirm('是否确定删除？')) {
            return false;
        }
        $.post("/novel/book/delChapter.html", {id:id},function (res) {
            if (res.code == 0) {
                alertMsg('success', res.msg)
                window.location.reload();
            } else if(res.code == 200) {
                alertMsg('error', res.msg)
                setTimeout(function(){ window.location.reload(); }, 2000);
            } else {
                alertMsg('error', res.msg)
            }
        });
    }
</script>