<div class="row">
    <div class="col-xs-12">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title"><?=$title?></h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <form class="form-horizontal" method="post" action="">
                <div class="box-body">
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-2 control-label">书名</label>
                        <div class="col-sm-10">
                            <input type="text" name="book_name" class="form-control" value="<?=$book['book_name'] ?? ''?>" size="40"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-2 control-label">分类</label>
                        <div class="col-sm-10">
                            <select name="book_category">
                                <option value="0">请选择分类</option>
                                <?php if(!empty($category)):foreach ($category as $key => $val):?>
                                    <option value="<?=$key?>" <?php if ((int)$key === (int)$book['book_category'])echo 'selected'?>><?=$val?></option>
                                <?php endforeach;endif;?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-2 control-label">作者</label>
                        <div class="col-sm-10">
                            <input type="text" name="book_author" class="form-control" value="<?=$book['book_author'] ?? ''?>"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-2 control-label">状态</label>
                        <div class="col-sm-10">
                            <label><input type="radio" name="book_state" value="0" <?php if((int)$book['book_state'] === 0)echo 'checked="checked"'?>> 连载中</label>
                            <label><input type="radio" name="book_state" value="1" <?php if((int)$book['book_state'] === 1)echo 'checked="checked"'?>> 已完成</label>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-2 control-label">关键字</label>
                        <div class="col-sm-10">
                            <input type="text" name="book_keyword" class="form-control" value="<?=$book['book_keyword'] ?? ''?>"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-2 control-label">简介</label>
                        <div class="col-sm-10">
                            <textarea name="book_intro" class="form-control" rows="5"><?=$book['book_intro'] ?? ''?></textarea>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-2 control-label">封面</label>
                        <div class="col-sm-10">
                            <input type="text" name="book_img" value="<?=$book['book_img'] ?? ''?>" size="80"/> <img src="<?=$book['book_img'] ?? ''?>" id="bookImg" width="40" height="50"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-2 control-label">监控采集</label>
                        <div class="col-sm-10">
                            <label><input type="radio" name="monitoring" value="1" <?php if((int)$book['book_is_collect'] === 1)echo 'checked="checked"'?> > 监控</label>
                            <label><input type="radio" name="monitoring" value="0" <?php if((int)$book['book_is_collect'] === 0)echo 'checked="checked"'?>> 不监控</label>
                        </div>
                    </div>
                </div>
                <!-- /.box-body -->

                <div class="box-footer">
                    <div class="col-sm-2"></div>
                    <div class="col-sm-10">
                        <input id="uploaderInput" style="display: none" class="weui-uploader__input" type="file" accept="image/*" multiple="">
                        <button type="submit" class="btn btn-primary btnSubmit">保存</button>
                    </div>
                </div>
            </form>
        </div>
        <!-- /.box -->
    </div>
    <!-- /.col -->
</div>
<!-- /.row -->
<script>
    $(function () {
        $('.btnSubmit').click(function(){
            if($('#name').val() == '') {
                alertMsg('error', '栏目名称不能为空');
                return false;
            }
        });
        $('#bookImg').click(function () {
            $('#uploaderInput').click();
        });

    })
</script>