<div class="row">
    <div class="col-xs-12">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title"><?=$title?></h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <form class="form-horizontal" method="post" action="">
                <div class="box-body">
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-2 control-label">文章标题</label>
                        <div class="col-sm-10">
                            <input type="text" name="title" id="title" class="form-control" value="<?=$article['title'] ?? $articleTitle?>" size="40"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-2 control-label">所属章节</label>
                        <div class="col-sm-10">
                            <select name="chapter_id" id="chapter_id" class="form-control">
                                <option value="0">请选择所属章节</option>
                                <?php if(!empty($chapters)):foreach ($chapters as $key => $val):?>
                                    <option value="<?=$key?>" <?php if ((int)$key === (int)$article['chapter_id'])echo 'selected'?>><?=$val?></option>
                                <?php endforeach;endif;?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-2 control-label">文章排序</label>
                        <div class="col-sm-10">
                            <input type="text" name="article_sort" id="article_sort" class="form-control" value="<?=$article['article_sort'] ?? $sort?>"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-2 control-label">OSS url</label>
                        <div class="col-sm-10"><?=$article['url'] ?? ''?></div>
                    </div>
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-2 control-label">内容</label>
                        <div class="col-sm-10">
                            <textarea name="content" id="content" class="form-control"><?=$article['content'] ?? ''?></textarea>
                        </div>
                    </div>
                </div>
                <!-- /.box-body -->

                <div class="box-footer">
                    <div class="col-sm-2"></div>
                    <div class="col-sm-10">
                        <button type="submit" class="btn btn-primary btnSubmit">保存</button>
                    </div>
                </div>
            </form>
        </div>
        <!-- /.box -->
    </div>
    <!-- /.col -->
</div>
<!-- /.row -->
<script src="/dist/plugins/plupload/plupload.full.min.js"></script>
<script src="/dist/plugins/ckeditor/ckeditor.js"></script>
<script>
    $(function () {
        $('.btnSubmit').click(function(){
            if($('#title').val() == '') {
                alertMsg('error', '文章标题不能为空');
                return false;
            }
            if($('#chapter_id').val() == 0) {
                alertMsg('error', '请选择所属章节');
                return false;
            }
            if($('#article_sort').val() == '') {
                alertMsg('error', '文章排序不能为空');
                return false;
            }
        });
        CKEDITOR.replace('content', {
            filebrowserImageUploadUrl:"/index/upload/editorUpload.html?type=<?=$moduleName?>",
            pasteUploadFileApi:"/index/upload/editorUpload.html?type=<?=$moduleName?>"
        });
    })
</script>