<div class="row">
    <div class="col-xs-12">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title"><?=$title?></h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <form class="form-horizontal" method="post" action="">
                <div class="box-body">
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-2 control-label">分卷名称</label>
                        <div class="col-sm-10">
                            <input type="text" name="chapter_name" id="chapter_name" class="form-control" value="<?=$chapter['chapter_name'] ?? ''?>" size="40"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-2 control-label">分卷排序</label>
                        <div class="col-sm-10">
                            <input type="text" name="chapter_order" id="chapter_order" class="form-control" value="<?=$chapter['chapter_order'] ?? 50?>"/>
                        </div>
                    </div>
                </div>
                <!-- /.box-body -->

                <div class="box-footer">
                    <div class="col-sm-2"></div>
                    <div class="col-sm-10">
                        <button type="submit" class="btn btn-primary btnSubmit">保存</button>
                    </div>
                </div>
            </form>
        </div>
        <!-- /.box -->
    </div>
    <!-- /.col -->
</div>
<!-- /.row -->
<script src="/dist/plugins/plupload/plupload.full.min.js"></script>
<script src="/dist/plugins/ckeditor/ckeditor.js"></script>
<script>
    $(function () {
        $('.btnSubmit').click(function(){
            if($('#chapter_name').val() == '') {
                alertMsg('error', '分卷名称不能为空');
                return false;
            }
            if($('#chapter_order').val() == '') {
                alertMsg('error', '分卷排序不能为空');
                return false;
            }
        });
    })
</script>