<!-- DataTables -->
<link rel="stylesheet" href="/dist/plugins/datatables.net-bs/css/dataTables.bootstrap.min.css">
<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title"><?= $title ?></h3>
                <div class="pull-right box-tools">
<!--                    <a href="/novel/collect/set.html" class="btn btn-default"><i class="fa fa-plus"></i></a>-->
                </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <table id="example2" class="table table-bordered table-hover">
                    <thead>
                    <tr>
                        <th width="20">ID</th>
                        <th>会员名</th>
                        <th width="100">登录次数</th>
                        <th width="100">最后登录IP</th>
                        <th width="140">最后登录时间</th>
                        <th width="140">注册时间</th>
                        <th width="80">操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php if (!empty($data)): ?>
                        <?php foreach ($data as $val): ?>
                            <tr>
                                <td><?= $val['id'] ?></td>
                                <td><?= $val['username'] ?></td>
                                <td><?= $val['count'] ?></td>
                                <td><?= $val['last_ip'] ?></td>
                                <td><?= $val['last_time'] == '1970-01-01 08:00:00' ? '' : $val['last_time'] ?></td>
                                <td><?= $val['create_at'] == '1970-01-01 08:00:00' ? '' : $val['create_at'] ?></td>
                                <td>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    <?php else:?>
                        <tr><td colspan="7" class="text-center">暂无数据</td></tr>
                    <?php endif; ?>
                    </tbody>
                </table>
                <div class="row text-center" id="pageList">
                </div>
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
    <!-- /.col -->
</div>
<!-- /.row -->
<script src="/dist/plugins/datatables.net/js/jquery.dataTables.min.js"></script>
<script src="/dist/plugins/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
<script>
    $(function () {
        pageHtml(<?=$page?>, <?=$totalPage?>, '<?=$pageLink?>');
    })
</script>